### ISSUE TITLE
What's your laptop config like?

### ISSUE THREAD

**Issue by sreetamdas** [SaraVieira/AMA#3]
What're the different tools that you use on a regular basis?
Favorite text editor?
Any particular music that you listen to while coding?

**Comment by SaraVieira** [comment]
Hello ! 🎉

> What're the different tools that you use on a regular basis?

I use Spotify, Hyper, Rambox, polymail on a daily basis and of course Chrome and VSCode for my coding.

> Favorite text editor?

My favorite text editor is Atom but It was eating way too much RAM in my PC so I had to switch to VSCode, I'm pretty happy with it but kind of miss the customization of Atom. It's kinda like having a iOS or Android.

> Any particular music that you listen to while coding?

This one is kind of embarrassing, so the emo kid in me never actually grew up so I mainly listen to rock and punk music while coding.
Some of my Favorite Bands:
     * https://open.spotify.com/artist/6om12Ev5ppgoMy3OYSoech
     * https://open.spotify.com/artist/7qAcXJgt1PWnxwUgxMdyuk
     * https://open.spotify.com/artist/74eX4C98E4FCrAMl39qRsJ

Sorry I don't the normal answer of listening to slow music 😞
