### ISSUE TITLE
Advices for junior Front-End developer

### ISSUE THREAD

**Issue by manuelteixeira** [SaraVieira/AMA#5]
Hi, 
Do you have some recommendations for books, courses and other resources for a junior?
Any other advices? 😁
Thanks!

**Comment by SaraVieira** [comment]
Hello !

Well I learned everything I know from the internet so some awesome stuff are:
    - egghead.io
    - https://www.youtube.com/user/ChromeDevelopers
    - scotch.io
    - https://www.youtube.com/user/kentdoddsfamily
    - https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q
    - https://www.youtube.com/channel/UCRZIRupy8-ZXx877Aa0joCQ
    - https://www.youtube.com/channel/UCP_lo1MFyx5IXDeD9s_6nUw
    - https://www.youtube.com/channel/UCyIe-61Y8C4_o-zZCtO4ETQ
    - https://dev.to/
  
When it comes to advice all I have to tell you is to build stuff, even if they are dumb. Just have fun and build stuff 🎉

Anything else don't hesistate to DM me on twitter
