### ISSUE TITLE
How did you get your first job?

### ISSUE THREAD

**Issue by morajabi** [SaraVieira/AMA#6]

**Comment by SaraVieira** [comment]
Hello !

I didn't go to college instead I went to this one year course that offered an internship for 3 months and when that internship was over they hired me as junior developer, I was working on Wordpress at the time

**Comment by morajabi** [comment]
Can I ask you where are you now, Sara?

**Comment by SaraVieira** [comment]
Sure! I am actually starting today at yld.io

**Comment by morajabi** [comment]
@SaraVieira Oh! Congrats, Sara!

**Comment by SaraVieira** [comment]
Thanks man 😁
